# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f7f86025d5c8b91a5e1ec61287ba0b3fc8de5fd06159ea6bd9c2dcd87f817c5e5a7a668aab34ab22aa25cafdfcfb3427ec675f5bee093834561977d95f58b8

test:
  secret_key_base: 34d0ddc75a47e8b2fc285744c2cb73b052c1c0010d3091a4edad22a3273f544a3e82bdf882ab3d6d411cca2f5c92c4c65570afb4bb55c250461af885a884d594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
